spring:
  application:
    name: service-activity
  profiles:
    active: dev
  cloud:
    nacos:
      discovery:
        server-addr: 10.10.93.58:8848
        username: nacos
        password: nacos